spring:
  datasource:
    url: jdbc:mysql:///dentistry?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    name: dentistry
    username: root
    password: 123456

dentistry:
  core:
    base:
      storage:
        disk:
          base-directory: C:/image
          base-url: /api/img
    message:
      sms:
        verification:
          maxRetryCount: 5
          dailyMaximumEachIp: 50
          intervalInSeconds: 60
          defaultValidityInMinutes: 5
          defaultTemplate: message/sms/verification/default.mustache
          types:
            login:
              templateId: SMS_60680199
              template: message/sms/verification/login.mustache
            borrowRequest:
              template: message/sms/verification/borrowRequest.mustache

wx:
  domain: http://tanghuaxiong.ymys.usooft.com
  appId: wxfcffb0d00f2da17b
  appSecret: 2fcf880c2503141e09bb0a55623f82f1
  app_id: wx6ae9aead2a926769
  app_secret: efc112848c7333b5b75f26345cf2e713
  pay:
    mchid: 1598795591
    privateKey: H8yNsA87UxM9a5jcTbPGJ0KPUuOaHByY
    notifyUrl: ${wx.domain}/api/enroll/notify