server:
  servlet:
    session:
      cookie:
        name: sid
      tracking-modes: cookie
  port: 8081

spring:
  profiles:
    include: core
    active: @spring.profiles.active@
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB